### ISSUE TITLE
failing to render excalidraw image when filesize is too large

### ISSUE THREAD

**Issue by mariotoffia** [Mogztter/asciidoctor-kroki#194]
Hi @Mogztter and I do really apprechiate all you do for asciidoctor! :)

I've transferred the issue I've filed at [kroki](https://github.com/yuzutech/kroki/issues/555).

"I'm using excalidraw via asciidoc-kroki (from @Mogztter) - It seems that if the file gets to big or too many objects in the drawing it will fail to render the svg image. Attached both JSON files respective images of failing and the one working."

Success image
![sucess-image](https://user-images.githubusercontent.com/1716527/105137172-2dfc6300-5af3-11eb-831e-774e29ac0dcc.png)

Failure
![failing_excalidraw](https://user-images.githubusercontent.com/1716527/105137188-35237100-5af3-11eb-8fbf-1f04378ea161.png)

The files that one is succeeding and the other is failing
[json-files.zip](https://github.com/Mogztter/asciidoctor-kroki/files/5840563/json-files.zip)

Cheers,
 Mario :)

**Comment by mariotoffia** [comment]
Just a quick follow-up question, you mentioned that one may increase the body size when self hosting - I've tried to set it to 1MB (since excalidraw seems to have 1m limit in it's server - https://github.com/yuzutech/kroki/blob/master/excalidraw/src/index.js#L14).

I've set the `KROKI_BODY_LIMIT` (https://github.com/yuzutech/kroki/blob/2bd2e664701f38877ba7ae75bfd833d0e1e5c0e7/server/src/main/java/io/kroki/server/Server.java#L67) environment variable in my docker compose - but it won't even log out that it tries to render it (failing json in above files). Is this incorrect way of increasing the body size?

my docker compose

```yaml
version: "3"
services:
  core:
    image: yuzutech/kroki
    environment:
      - KROKI_BLOCKDIAG_HOST=blockdiag
      - KROKI_MERMAID_HOST=mermaid
      - KROKI_BPMN_HOST=bpmn
      - KROKI_EXCALIDRAW_HOST=excalidraw
      - KROKI_BODY_LIMIT=1048576
    ports:
      - "8000:8000"
  blockdiag:
    image: yuzutech/kroki-blockdiag
    expose:
      - "8001"
  mermaid:
    image: yuzutech/kroki-mermaid
    expose:
      - "8002"
  bpmn:
    image: yuzutech/kroki-bpmn
    expose:
      - "8003"
  excalidraw:
    image: yuzutech/kroki-excalidraw
    expose:
      - "8004"
```

Cheers,
 Mario :)
